version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=murphydb
      - POSTGRES_USER=murphy
      - POSTGRES_PASSWORD=murphy123
    ports:
      - 5432:5432
volumes:
  postgres-db:
